version: "3.9"
services:
  backend:
    restart: unless-stopped
    image: backend
    ports:
      - 5001:5000
    env_file:
      - .env
    container_name: Bookkeeping-backend
    networks:
      - default  
